# .air.toml
# Config for air, a live-reloader for Go applications.
# Place this file in the root of each Go service.

# The root directory of your project
root = "."
tmp_dir = "tmp"

[build]
# Command to build your application.
cmd = "go build -o ./auth main.go"
# The binary to run.
bin = "./auth"
# Watch these file extensions.
include_ext = ["go", "tpl", "tmpl", "html"]
# Ignore these directories.
exclude_dir = ["assets", "tmp", "vendor"]
# Log file for build errors.
log = "air_errors.log"
# Delay between file system events and build.
stop_on_error = true
send_interrupt = true
poll = true
poll_interval = 500
delay = 1000

[log]
# Show time in logs.
time = true

[color]
# Customize colors.
main = "yellow"
watcher = "cyan"
build = "blue"
runner = "green"

[misc]
# Delete tmp folder on exit
clean_on_exit = true
